jobs:
  build:
    runs-on: ubuntu-latest
    steps:

  e2e:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install

      - id: preview
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "--name ${{ github.run_id }}"

      - name: Install Playwright
        run: bunx playwright install --with-deps chromium

      - name: xvfb + Test
        env:
          WALLET_MNEMONIC: ${{ secrets.WALLET_MNEMONIC }}
          BASE_URL: ${{ steps.preview.outputs.preview-url }}
        run: |
          sudo apt-get install -y xvfb
          xvfb-run bun test  # Your playwright.config uses BASE_URL

  deploy:
    needs: [build, e2e]
    if: github.ref == 'refs/heads/main'
